import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { SimulationResult } from '@/lib/aggregation/types';
import { Scenario } from '@/lib/shared/portfolioStore';

export const generatePDFReport = (
    scenarioName: string,
    results: SimulationResult,
    year: string | number,
    charts: { cfe?: string; generation?: string } // Base64 images
) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 14;

    // --- Header ---
    doc.setFillColor(10, 20, 40); // Navy 950
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.text('Eighty760', margin, 20);

    doc.setFontSize(12);
    doc.setTextColor(0, 255, 136); // Energy Green
    doc.text('24/7 Carbon-Free Energy Report', margin, 32);

    doc.setFontSize(10);
    doc.setTextColor(200, 200, 200);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - margin, 20, { align: 'right' });
    doc.text(`Scenario: ${scenarioName} (${year})`, pageWidth - margin, 32, { align: 'right' });

    // --- Metrics Section ---
    let yPos = 55;

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Key Performance Indicators', margin, yPos);

    yPos += 10;

    const metrics = [
        ['CFE Score', `${(results.cfe_score * 100).toFixed(1)}%`],
        ['Net Cost', `$${results.total_cost_net.toLocaleString(undefined, { maximumFractionDigits: 0 })}`],
        ['Avg Cost', `$${results.avg_cost_per_mwh.toFixed(2)}/MWh`],
        ['Grid Deficit', `${(results.total_load_mwh - results.total_matched_mwh).toLocaleString(undefined, { maximumFractionDigits: 0 })} MWh`],
        ['Clean Gen', `${results.total_gen_mwh.toLocaleString(undefined, { maximumFractionDigits: 0 })} MWh`]
    ];

    autoTable(doc, {
        startY: yPos,
        head: [['Metric', 'Value']],
        body: metrics,
        theme: 'striped',
        headStyles: { fillColor: [0, 20, 40] },
        styles: { fontSize: 10, cellPadding: 4 },
        columnStyles: { 0: { fontStyle: 'bold' } },
        margin: { left: margin, right: pageWidth / 2 + 5 } // Half width
    });

    // --- Add Charts ---
    // If we have charts, place them. For now, assuming distinct placement.
    // Placement logic could be refined based on actual chart aspect ratios.

    const tableEnd = (doc as any).lastAutoTable.finalY + 15;
    yPos = Math.max(yPos, tableEnd);

    if (charts.cfe) {
        // Add CFE Chart Image
        // Assuming 16:9 or similar ratio
        const imgWidth = pageWidth - (margin * 2);
        const imgHeight = 80;

        doc.text('24/7 CFE vs Load Profile', margin, yPos);
        yPos += 5;
        doc.addImage(charts.cfe, 'PNG', margin, yPos, imgWidth, imgHeight);
        yPos += imgHeight + 15;
    }

    if (charts.generation) {
        if (yPos > 250) {
            doc.addPage();
            yPos = 20;
        }
        doc.text('Generation Mix', margin, yPos);
        yPos += 5;
        // doc.addImage(charts.generation, 'PNG', margin, yPos, imgWidth, imgHeight); 
        // Need to pass charts.generation if meaningful
    }

    // --- Disclaimer ---
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('This report is generated by Eighty760 based on simulated data. Actual results may vary.', margin, pageHeight - 10);

    doc.save(`Eighty760_Report_${scenarioName.replace(/\s+/g, '_')}.pdf`);
};
